// swift-tools-version: 5.9
import PackageDescription

// Swift Package Manager manifest for the Replayfy Flutter plugin (iOS).
//
// Flutter is moving toward SPM as the default iOS plugin integration; this
// manifest makes the plugin SPM-ready. The CocoaPods podspec is kept
// alongside for projects still on CocoaPods — Flutter uses whichever the host
// app has enabled. The Swift sources live under Sources/replayfy_flutter so
// both build systems point at the same files.
let package = Package(
  name: "replayfy_flutter",
  platforms: [
    .iOS("15.0"),
  ],
  products: [
    .library(name: "replayfy-flutter", targets: ["replayfy_flutter"]),
  ],
  dependencies: [
    // The Flutter engine package — generated by the Flutter tool next to this
    // manifest when Swift Package Manager is enabled. Gives the plugin
    // `import Flutter`.
    .package(name: "FlutterFramework", path: "../FlutterFramework"),
    // The native iOS SDK that does the real recording. Path dependency for
    // local development against the sibling checkout; a published release
    // pins a versioned git/registry reference instead (the podspec resolves
    // the same SDK via `s.dependency 'Replay'`).
    .package(name: "Replay", path: "../../../replay-ios-sdk"),
  ],
  targets: [
    .target(
      name: "replayfy_flutter",
      dependencies: [
        .product(name: "FlutterFramework", package: "FlutterFramework"),
        .product(name: "Replay", package: "Replay"),
      ]
    ),
  ]
)
