name: replayfy_flutter
description: Session replay, product analytics and error monitoring for your Flutter apps on iOS and Android.
version: 0.0.1
homepage: https://replayfy.app
repository: https://github.com/replayfy/flutter

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.replayfy.flutter
        pluginClass: ReplayfyFlutterPlugin
      ios:
        pluginClass: ReplayfyFlutterPlugin
